onEvent('recipes', event => {
	function backAndForth(inputItem, outputItem) {
		onEvent('recipes', event => {
			event.remove({output: inputItem})
			event.remove({output: outputItem})
		event.shapeless(inputItem, [outputItem])
		event.shapeless(outputItem, [inputItem])
	})}
	event.shapeless('create:rose_quartz', ["#forge:gems/quartz","4x #forge:dusts/redstone"])
	backAndForth('1x thermal:press_gear_die', 'immersiveengineering:mold_gear')
	event.shapeless('extendedcrafting:basic_table', ['minecraft:crafting_table', 'iron_block'])
	backAndForth('multiblocked:fluid_input','multiblocked:fluid_output')
	backAndForth('multiblocked:energy_input','multiblocked:energy_output')
	backAndForth('multiblocked:item_output','multiblocked:item_input')
	event.shapeless('multiblocked:energy_output','multiblocked:energy_input')
	event.shapeless('delightful:field_salad', ['#forge:salad_ingredients','#forge:salad_ingredients', '#forge:cooked_beef', 'minecraft:carrot', '#forge:fruits/sweet'])
	event.shapeless('delightful:deluxe_cheeseburger', ['#forge:bread', '#forge:cooked_beef', '#forge:cheese_or_milk', '#forge:cooked_beef', '#forge:cheese_or_milk', '#forge:cooked_bacon','#forge:salad_ingredients','#forge:crops/tomato', '#forge:crops/onion'])
	event.shapeless('delightful:deluxe_cheeseburger', ['delightful:cheeseburger', '#forge:cooked_beef', '#forge:cheese_or_milk', '#forge:cooked_bacon'])
	event.shapeless('farmersdelight:steak_and_potatoes', ['minecraft:baked_potato', '#forge:cooked_beef', 'minecraft:bowl', '#forge:crops/onion', 'farmersdelight:cooked_rice'])
	event.shapeless('delightful:cheeseburger', ['farmersdelight:hamburger', '#forge:cheese_or_milk'])
	event.shapeless('delightful:cheeseburger', ['#forge:bread', '#forge:cheese_or_milk', '#forge:salad_ingredients','#forge:crops/tomato', '#forge:crops/onion'])
	event.shapeless('2x farmersdelight:barbecue_stick', ['#forge:crops/onion','#forge:crops/tomato', '#forge:cooked_beef', '#forge:cooked_chicken','#forge:rods/wooden','#forge:rods/wooden' ])
	event.shapeless('farmersdelight:hamburger', ['#forge:bread', '#forge:cooked_beef', '#forge:salad_ingredients', '#forge:crops/tomato', '#forge:crops/onion'])
	backAndForth('industrialforegoing:fluid_collector', 'industrialforegoing:fluid_placer')
	backAndForth('industrialforegoing:block_breaker','industrialforegoing:block_placer')
	event.shapeless('4x bloodmagic:throwing_dagger_syringe',['#forge:rods/wooden', '#forge:string', '#forge:glass'])
	event.shapeless('4x bloodmagic:throwing_dagger',['#forge:rods/wooden', '#forge:string', '#forge:ingots/iron'])
	event.shapeless('4x bloodmagic:amethystthrowingdagger',['#forge:rods/wooden', '#forge:string', '#forge:gems/amethyst'])
	backAndForth('bloodmagic:inputroutingnode','bloodmagic:outputroutingnode')
	event.shapeless('3x farmersdelight:rope','6x #forge:string')
	event.shapeless('2x farmersdelight:rope','6x #forge:fiber_hemp')
	event.shapeless('1x farmersdelight:rope','6x farmersdelight:straw')
	event.shapeless('bloodmagic:sacrificialdagger', 'farmersdelight:golden_knife')
	event.shapeless('thermal:slag_block', '4x #forge:slag')
	event.shapeless('4x create:belt_connector','6x thermal:cured_rubber')
	event.shapeless('2x create:belt_connector','6x immersiveengineering:ersatz_leather')
	event.shapeless('thermal:glowstone_mushroom_spores', ['#forge:mushrooms', '#forge:dusts/glowstone', '#forge:fertilizer', 'minecraft:experience_bottle'])
	event.shapeless('thermal:redstone_mushroom_spores', ['#forge:mushrooms', '#forge:dusts/redstone', '#forge:fertilizer', 'minecraft:experience_bottle'])
	event.shapeless('thermal:slime_mushroom_spores', ['#forge:mushrooms', '#bookshelf:slime_balls', '#forge:fertilizer', 'minecraft:experience_bottle'])
	event.shapeless('thermal:gunpowder_mushroom_spores', ['#forge:mushrooms', '#forge:gunpowder', '#forge:fertilizer', 'minecraft:experience_bottle'])
	event.shapeless('4x immersiveengineering:connector_lv',['immersiveengineering:coil_lv', '2x #immersiveengineering:connector_insulator','#forge:plates/constantan'])
	event.shapeless('4x immersiveengineering:connector_mv',['immersiveengineering:coil_mv', '2x #immersiveengineering:connector_insulator','#forge:plates/electrum'])
	event.shapeless('4x immersiveengineering:connector_hv',['immersiveengineering:coil_hv', '2x #immersiveengineering:connector_insulator','#forge:plates/steel', '#forge:plates/aluminum'])
	event.shapeless('4x immersiveengineering:connector_redstone',['extendedcrafting:redstone_ingot_block', '2x #immersiveengineering:connector_insulator','#forge:plates/brass'])
	event.shapeless('2x mekanism:enriched_iron', ['#forge:dusts/steel', '#forge:dusts/hop_graphite'])
	backAndForth('mekanism:fluidic_plenisher', 'mekanism:electric_pump')
	backAndForth('mekanism:basic_logistical_transporter', 'mekanism:restrictive_transporter')
	backAndForth('mekanism:qio_exporter', 'mekanism:qio_importer')
})
    onEvent('recipes', event => {
        event.forEachRecipe({type: 'minecraft:crafting_shaped', output: '#minecraft:slabs' }, r => {
            var slab = r.outputItems[0]
            var block = r.inputItems[0]
            event.shapeless(Item.of(block, 1) ,Ingredient.of(slab, 2))
            })
    })