onEvent('recipes', event => {
	event.shapeless('create:rose_quartz', ["minecraft:quartz","#forge:dusts/redstone","#forge:dusts/redstone","#forge:dusts/redstone","#forge:dusts/redstone"])
	event.shapeless('1x thermal:press_gear_die', ['immersiveengineering:mold_gear'])
	event.shapeless('1x immersiveengineering:mold_gear', ['thermal:press_gear_die'])
	event.shapeless('extendedcrafting:basic_table', ['minecraft:crafting_table', 'iron_block'])
	event.shapeless('multiblocked:fluid_input','multiblocked:fluid_output')
	event.shapeless('multiblocked:item_input','multiblocked:item_output')
	event.shapeless('multiblocked:energy_input','multiblocked:energy_output')
	event.shapeless('multiblocked:fluid_output','multiblocked:fluid_input')
	event.shapeless('multiblocked:item_output','multiblocked:item_input')
	event.shapeless('multiblocked:energy_output','multiblocked:energy_input')
	event.shapeless('delightful:field_salad', ['#forge:salad_ingredients','#forge:salad_ingredients', '#forge:cooked_beef', 'minecraft:carrot', '#forge:fruits/sweet'])
	event.shapeless('delightful:deluxe_cheeseburger', ['#forge:bread', '#forge:cooked_beef', '#forge:cheese_or_milk', '#forge:cooked_beef', '#forge:cheese_or_milk', '#forge:cooked_bacon','#forge:salad_ingredients','#forge:crops/tomato', '#forge:crops/onion'])
	event.shapeless('delightful:deluxe_cheeseburger', ['delightful:cheeseburger', '#forge:cooked_beef', '#forge:cheese_or_milk', '#forge:cooked_bacon'])
	event.shapeless('farmersdelight:steak_and_potatoes', ['minecraft:baked_potato', '#forge:cooked_beef', 'minecraft:bowl', '#forge:crops/onion', 'farmersdelight:cooked_rice'])
	event.shapeless('delightful:cheeseburger', ['farmersdelight:hamburger', '#forge:cheese_or_milk'])
	event.shapeless('delightful:cheeseburger', ['#forge:bread', '#forge:cheese_or_milk', '#forge:salad_ingredients','#forge:crops/tomato', '#forge:crops/onion'])
	event.shapeless('2x farmersdelight:barbecue_stick', ['#forge:crops/onion','#forge:crops/tomato', '#forge:cooked_beef', '#forge:cooked_chicken','#forge:rods/wooden','#delightfulforge:rods/wooden' ])
	event.shapeless('farmersdelight:hamburger', '#forge:bread', '#forge:cooked_beef', '#forge:salad_ingredients', '#forge:crops/tomato', '#forge:crops/onion')
})