onEvent('recipes', event => {
     const { smelter, press, crucible, compression_fuel, centrifuge, pyrolyzer, pulverizer } = event.recipes.thermal
     smelter('4x extendedcrafting:redstone_ingot',['#forge:ingots/steel', 'minecraft:redstone_block'])
     smelter('3x extendedcrafting:black_iron_ingot',['3x #forge:ingots/manasteel', '#botania:petals/black'])
     smelter('3x appliedenergistics2:silicon',['#forge:dusts/charcoal', '#forge:dusts/quartz', "minecraft:sand"])
     press('thermal:diamond_gear', ['4x minecraft:diamond', 'thermal:press_gear_die'])
     crucible(Fluid.of('kubejs:pure_inferium',250), 'mysticalagriculture:inferium_essence')
     crucible(Fluid.of('kubejs:pure_tertium',250), 'mysticalagriculture:tertium_essence')
     crucible(Fluid.of('kubejs:pure_imperium',250),'mysticalagriculture:imperium_essence')
     crucible(Fluid.of('kubejs:pure_prudentium',250), 'mysticalagriculture:prudentium_essence')
     crucible(Fluid.of('kubejs:pure_supremium',250), 'mysticalagriculture:supremium_essence')
     crucible(Fluid.of('tconstruct:blazing_blood',50), 'minecraft:blaze_powder')
     compression_fuel(Fluid.of('kubejs:pure_inferium',1000)).energy(25000)
     compression_fuel(Fluid.of('kubejs:pure_prudentium',1000)).energy(50000)
     compression_fuel(Fluid.of('kubejs:pure_tertium',1000)).energy(75000)
     compression_fuel(Fluid.of('kubejs:pure_imperium',1000)).energy(100000)
     compression_fuel(Fluid.of('kubejs:pure_supremium',1000)).energy(150000)
     compression_fuel(Fluid.of('immersiveengineering:creosote',1000)).energy(75000)
     centrifuge(['minecraft:slime_ball', Fluid.of('minecraft:lava', 250)],'minecraft:magma_cream')
     pulverizer('mekanism:dust_charcoal','minecraft:charcoal')
})