onEvent('recipes', event => {
     const { smelter, press, crucible, compression_fuel, centrifuge, pyrolyzer, pulverizer, refinery, magmatic_fuel, bottler } = event.recipes.thermal
     
     smelter('3x refinedstorage:silicon',['#forge:dusts/charcoal', '#forge:dusts/quartz', "#forge:sand"])
     smelter('4x refinedstorage:quartz_enriched_iron',['3x mekanism:enriched_iron', "#forge:ingots/lead", '4x #forge:gems/quartz'])
     smelter('2x extendedcrafting:ender_ingot',['#forge:ingots/steel', 'create:shadow_steel', '#forge:ender_pearls'])
     smelter('1x extendedcrafting:redstone_ingot',['#forge:ingots/manasteel', 'thermal:redstone_mushroom_spores'])
     smelter('3x extendedcrafting:black_iron_ingot',['2x #forge:ingots/manasteel', '#forge:bitumen', 'thermal:gunpowder_mushroom_spores'])
     smelter('3x mekanismgenerators:reactor_glass',['2x #forge:ingots/lead', '4x mekanism:enriched_iron', '3x #thermal:glass/hardened'])
     
     press('thermal:diamond_gear', ['4x minecraft:diamond', 'thermal:press_gear_die'])
     
     magmatic_fuel(Fluid.of('kubejs:pure_inferium', 1000)).energy(25000)
     magmatic_fuel(Fluid.of('kubejs:pure_prudentium', 1000)).energy(50000)
     magmatic_fuel(Fluid.of('kubejs:pure_tertium', 1000)).energy(75000)
     magmatic_fuel(Fluid.of('kubejs:pure_imperium', 1000)).energy(100000)
     magmatic_fuel(Fluid.of('kubejs:pure_supremium', 1000)).energy(150000)
     centrifuge([Item.of('minecraft:redstone').withChance(0.33), Item.of('minecraft:glowstone_dust').withChance(0.33), Item.of('mna:purified_vinteum_dust').withChance(0.33)],'mna:vinteum_dust').energy(6000)
     centrifuge([Item.of('minecraft:iron_nugget').withChance(0.12), Item.of('#forge:nuggets/tin').withChance(0.06), Item.of('#forge:nuggets/nickel').withChance(0.06), Item.of('#forge:nuggets/lead').withChance(0.06)], 'minecraft:gravel')
     centrifuge([Item.of('thermal:niter_dust').withChance(0.12), Item.of('thermal:apatite_dust').withChance(0.12), Item.of('mekanism:dust_fluorite').withChance(0.15), Item.of('mekanism:dust_sulfur').withChance(0.15)], 'minecraft:sand')
     centrifuge([Item.of('thermal_extra:soul_sand_dust').withChance(0.12), Item.of('#forge:powders/blaze').withChance(0.10), Item.of('#forge:powders/basalz').withChance(0.06), Item.of('#forge:nuggets/gold').withChance(0.03)], 'create:cinder_flour')
     centrifuge([Item.of('create:cinder_flour').withChance(0.12), Item.of('#forge:powders/blitz').withChance(0.10), Item.of('#forge:powders/blizz').withChance(0.06), Item.of('malum:blazing_quartz_fragment').withChance(0.03)], 'thermal_extra:soul_sand_dust')
     centrifuge(['minecraft:slime_ball', Fluid.of('minecraft:lava', 250)],'minecraft:magma_cream').energy(5000)
     centrifuge(['malum:natural_quartz', Fluid.of('tconstruct:blazing_blood', 250)],'malum:blazing_quartz').energy(5000)
     centrifuge(['minecraft:dirt',Item.of('thermal:tar').withChance(0.20),Fluid.of('industrialforegoing:sludge', 125)],'malum:blighted_soil').energy(5000)
     centrifuge(['minecraft:dirt',Item.of('thermal:tar').withChance(0.20),Fluid.of('industrialforegoing:sludge', 125)],'malum:blighted_earth').energy(5000)
     centrifuge(['thermal:tar',Fluid.of('industrialforegoing:sludge', 125)],'malum:blighted_gunk').energy(5000)
     pulverizer('#forge:dusts/charcoal','#forge:charcoal')
     pulverizer('#forge:dusts/coal_coke','#forge:coal_coke')
     pulverizer('9x #forge:dusts/coal_coke','#forge:storage_blocks/coal_coke')

     refinery([Fluid.of('kubejs:p_biofuel', 75), Fluid.of('industrialforegoing:sludge', 15), Item.of('thermal:tar').withChance(0.1)], Fluid.of('kubejs:r_biofuel', 100))
     
     compression_fuel(Fluid.of('kubejs:p_biofuel', 1000)).energy(1500000)
     compression_fuel(Fluid.of('kubejs:r_biofuel', 1000)).energy(500000)
     compression_fuel(Fluid.of('kubejs:c_biofuel', 1000)).energy(250000)
     
     bottler('fluxnetworks:flux_dust', ['#forge:dusts/refined_obsidian', Fluid.of('tconstruct:molten_enderium', 180)])
     
     function soulInfused(inputItem, outputItem) {
          event.remove({output: outputItem})
          smelter(outputItem, [inputItem, '#forge:ingots/soul_infused', '#forge:gears/dragonsteel'])
     }
     function enderium(inputItem, outputItem) {
          event.remove({output: outputItem})
          smelter(outputItem, [inputItem, '#forge:gems/apatite', '#forge:gears/enderium'])
     }
     function shellite(inputItem, outputItem) {
          event.remove({output: outputItem})
          smelter(outputItem, [inputItem, '#forge:gems/cinnabar', '#forge:gears/shellite'])
     }
     function twinite(inputItem, outputItem) {
          event.remove({output: outputItem})
          smelter(outputItem, [inputItem, '#forge:gems/b_quartz', '#forge:gears/twinite'])
     }
     soulInfused('thermal:area_radius_augment', 'thermal_extra:area_radius_augment_1')
     soulInfused('thermal:potion_amplifier_augment', 'thermal_extra:potion_amplifier_augment_1')
     soulInfused('thermal:potion_duration_augment', 'thermal_extra:potion_duration_augment_1') 
     soulInfused('thermal:rf_coil_augment','thermal_extra:rf_coil_augment_1')
     soulInfused('thermal:rf_coil_storage_augment','thermal_extra:rf_coil_storage_augment_1')
     soulInfused('thermal:rf_coil_xfer_augment', 'thermal_extra:rf_coil_xfer_augment_1')
     soulInfused('thermal:fluid_tank_augment', 'thermal_extra:fluid_tank_augment_1')
     soulInfused('thermal:machine_speed_augment', 'thermal_extra:machine_speed_augment_1')
     soulInfused('thermal:machine_efficiency_augment','thermal_extra:machine_efficiency_augment_1')
     soulInfused('thermal:dynamo_output_augment', 'thermal_extra:dynamo_output_augment_1')
     soulInfused('thermal:dynamo_fuel_augment', 'thermal_extra:dynamo_fuel_augment_1') 
     soulInfused('thermal:machine_catalyst_augment', 'thermal_extra:machine_catalyst_augment_1') 
     soulInfused('thermal:machine_output_augment', 'thermal_extra:machine_output_augment_1')
     enderium('thermal_extra:area_radius_augment_1', 'thermal_extra:area_radius_augment_2')
     enderium('thermal_extra:potion_amplifier_augment_1', 'thermal_extra:potion_amplifier_augment_2')
     enderium('thermal_extra:potion_duration_augment_1', 'thermal_extra:potion_duration_augment_2') 
     enderium('thermal_extra:rf_coil_augment_1','thermal_extra:rf_coil_augment_2')
     enderium('thermal_extra:rf_coil_storage_augment_1','thermal_extra:rf_coil_storage_augment_2')
     enderium('thermal_extra:rf_coil_xfer_augment_1', 'thermal_extra:rf_coil_xfer_augment_2')
     enderium('thermal_extra:fluid_tank_augment_1', 'thermal_extra:fluid_tank_augment_2')
     enderium('thermal_extra:machine_speed_augment_1', 'thermal_extra:machine_speed_augment_2')
     enderium('thermal_extra:machine_efficiency_augment_1','thermal_extra:machine_efficiency_augment_2')
     enderium('thermal_extra:dynamo_output_augment_1', 'thermal_extra:dynamo_output_augment_2')
     enderium('thermal_extra:dynamo_fuel_augment_1', 'thermal_extra:dynamo_fuel_augment_2') 
     enderium('thermal_extra:machine_catalyst_augment_1', 'thermal_extra:machine_catalyst_augment_2') 
     enderium('thermal_extra:machine_output_augment_1', 'thermal_extra:machine_output_augment_2')
     shellite('thermal_extra:area_radius_augment_2', 'thermal_extra:area_radius_augment_3')
     shellite('thermal_extra:potion_amplifier_augment_2', 'thermal_extra:potion_amplifier_augment_3')
     shellite('thermal_extra:potion_duration_augment_2', 'thermal_extra:potion_duration_augment_3') 
     shellite('thermal_extra:rf_coil_augment_2','thermal_extra:rf_coil_augment_3')
     shellite('thermal_extra:rf_coil_storage_augment_2','thermal_extra:rf_coil_storage_augment_3')
     shellite('thermal_extra:rf_coil_xfer_augment_2', 'thermal_extra:rf_coil_xfer_augment_3')
     shellite('thermal_extra:fluid_tank_augment_2', 'thermal_extra:fluid_tank_augment_3')
     shellite('thermal_extra:machine_speed_augment_2', 'thermal_extra:machine_speed_augment_3')
     shellite('thermal_extra:machine_efficiency_augment_2','thermal_extra:machine_efficiency_augment_3')
     shellite('thermal_extra:dynamo_output_augment_2', 'thermal_extra:dynamo_output_augment_3')
     shellite('thermal_extra:dynamo_fuel_augment_2', 'thermal_extra:dynamo_fuel_augment_3') 
     shellite('thermal_extra:machine_catalyst_augment_2', 'thermal_extra:machine_catalyst_augment_3') 
     shellite('thermal_extra:machine_output_augment_2', 'thermal_extra:machine_output_augment_3')
     twinite('thermal_extra:area_radius_augment_3', 'thermal_extra:area_radius_augment_4')
     twinite('thermal_extra:potion_amplifier_augment_3', 'thermal_extra:potion_amplifier_augment_4')
     twinite('thermal_extra:potion_duration_augment_3', 'thermal_extra:potion_duration_augment_4') 
     twinite('thermal_extra:rf_coil_augment_3','thermal_extra:rf_coil_augment_4')
     twinite('thermal_extra:rf_coil_storage_augment_3','thermal_extra:rf_coil_storage_augment_4')
     twinite('thermal_extra:rf_coil_xfer_augment_3', 'thermal_extra:rf_coil_xfer_augment_4')
     twinite('thermal_extra:fluid_tank_augment_3', 'thermal_extra:fluid_tank_augment_4')
     twinite('thermal_extra:machine_speed_augment_3', 'thermal_extra:machine_speed_augment_4')
     twinite('thermal_extra:machine_efficiency_augment_3','thermal_extra:machine_efficiency_augment_4')
     twinite('thermal_extra:dynamo_output_augment_3', 'thermal_extra:dynamo_output_augment_4')
     twinite('thermal_extra:dynamo_fuel_augment_3', 'thermal_extra:dynamo_fuel_augment_4') 
})
