onEvent('recipes', event =>{
	event.recipes.createPressing('#forge:plates/iron','#forge:ingots/iron')
	event.recipes.createPressing('#forge:plates/copper','#forge:ingots/copper')
	event.recipes.createPressing('#forge:plates/tin','#forge:ingots/tin')
	event.recipes.createPressing('#forge:plates/lead','#forge:ingots/lead')
	event.recipes.createPressing('#forge:plates/silver','#forge:ingots/silver')
	event.recipes.createPressing('#forge:plates/nickel','#forge:ingots/nickel')
	event.recipes.createPressing('#forge:plates/steel','#forge:ingots/steel')
	event.recipes.createPressing('#forge:plates/aluminum','#forge:ingots/aluminum')
	event.recipes.createPressing('#forge:plates/gold','#forge:ingots/gold')
	event.recipes.createPressing('#forge:plates/uranium','#forge:ingots/uranium')
	event.recipes.createPressing('#forge:plates/constantan','#forge:ingots/constantan')
	event.recipes.createPressing('#forge:plates/invar','#forge:ingots/invar')
	event.recipes.createPressing('#forge:plates/electrum','#forge:ingots/electrum')
	event.recipes.createPressing('#forge:plates/bronze','#forge:ingots/bronze')
	event.recipes.createPressing('extendedcrafting:black_iron_slate', 'extendedcrafting:black_iron_ingot')
})